export const GAME_MODE_MAP = {
    "BlindDeck": "Blind Deck Challenge",
    "DoubleElixir": "Double Elixir Battle",
    "Invalid_1": "Invalid_1",
    "HeroChallenge_draft": "Heroes Challenge",
    "Invalid_2": "Invalid_2",
    "DraftMode": "Draft Battle",
    "Ladder": "Ladder",
    "Friendly": "1v1 Friendly Battle",
    "Training": "Training",
    "Tournament": "Normal Battle",
    "Challenge": "Normal Battle",
    "DoubleElixir_Friendly": "Double Elixir Battle",
    "Invalid_3": "Invalid_3",
    "DraftModeInsane": "Double Elixir Draft",
    "TeamVsTeam": "2v2 Battle",
    "RetroRoyale": "Retro Royale Challenge",
    "CardRelease": "CardRelease",
    "CardReleaseDraft": "Draft Battle",
    "PvE": "Puzzle Royale",
    "TvE": "Clan vs Enemy",
    "PvE_Boss": "Puzzle Royale",
    "PvE_Tutorial": "Puzzle Royale",
    "TeamVsTeamDraft": "2v2 Draft Battle",
    "TeamVsTeamLadder": "2v2 Battle",
    "Overtime_Tournament": "Sudden Death Battle",
    "GoldRush_Tournament": "Gold Rush",
    "TeamVsTeamChallenge": "2v2 Challenge",
    "TripleElixir_Tournament": "Triple Elixir Battle",
    "RampUpElixir_Tournament": "Ramp Up Battle",
    "TeamVsTeamCrowns": "2v2 Battle",
    "TeamVsTeamDraftChallenge": "2v2 Draft Battle",
    "Overtime_Friendly": "Sudden Death Battle",
    "TripleElixir_Friendly": "Triple Elixir Battle",
    "RampUpElixir_Friendly": "Ramp Up Battle",
    "TeamVsTeam_DoubleElixir_Friendly": "2v2 Double Elixir",
    "TeamVsTeam_DoubleElixir_Tournament": "2v2 Double Elixir",
    "TeamVsTeam_Overtime_Friendly": "2v2 Sudden Death",
    "TeamVsTeam_Overtime_Tournament": "2v2 Sudden Death",
    "TeamVsTeam_RampUpElixir_Friendly": "2v2 Ramp Up",
    "TeamVsTeam_RampUpElixir_Tournament": "2v2 Ramp Up",
    "TeamVsTeam_DraftModeInsane_Friendly": "2v2 Double Elixir Draft",
    "Invalid": "Invalid",
    "PickMode": "Mega Draft Challenge",
    "TeamVsTeamLadder_GoldRush": "Gold Rush",
    "Ladder_GoldRush": "Gold Rush",
    "Touchdown": "Touchdown",
    "TeamVsTeamLadder_GemRush": "TeamVsTeamLadder_GemRush",
    "Ladder_GemRush": "Ladder_GemRush",
    "GemRush_Tournament": "GemRush_Tournament",
    "TeamVsTeam_Touchdown": "2v2 Touchdown",
    "Touchdown_Draft": "Touchdown Draft",
    "TeamVsTeam_Touchdown_Draft": "2v2 Touchdown Draft",
    "MirrorDeck": "Mirror Battle",
    "TeamVsTeam_MirrorDeck": "2v2 Mirror Battle",
    "Friendly_FixedDeckOrder": "1v1 Fixed Deck Battle",
    "TeamVsTeam_FixedDeckOrder": "2v2 Fixed Deck Battle",
    "MirrorDeck_H": "Mirror Battle",
    "TeamVsTeam_MirrorDeck_H": "2v2 Mirror Battle",
    "KingOfTheHill": "King of the Hill",
    "ModernRoyale": "Modern Royale",
    "Overtime_Ladder": "Sudden Death Battle",
    "DoubleElixir_Ladder": "Double Elixir Battle",
    "TripleElixir_Ladder": "Triple Elixir Battle",
    "NOTINUSE1": "2v2 Double Elixir",
    "NOTINUSE2": "2v2 Double Elixir",
    "Showdown_Friendly": "1v1 Showdown",
    "Showdown_Ladder": "1v1 Showdown",
    "TeamVsTeam_DoubleElixir_Ladder": "2v2 Double Elixir",
    "TeamVsTeam_Overtime_Ladder": "2v2 Sudden Death",
    "CaptureTower_Friendly": "Capture Tower",
    "RampUpElixir_Ladder": "Ramp Up Battle",
    "Rage_Friendly": "Rage Battle",
    "MirrorDeck_CW": "Mirror Battle",
    "Rage_Ladder": "Rage Battle",
    "LavaFloor_Friendly": "Lava Floor Battle",
    "Event_NewArena1": "Arena 1 Deckbuilding Challenge",
    "Event_NewArena2": "Arena 2 Deckbuilding Challenge",
    "Event_NewArena3": "Arena 3 Deckbuilding Challenge",
    "Event_NewArena4": "Arena 4 Deckbuilding Challenge",
    "Event_NewArena5": "Arena 5 Deckbuilding Challenge",
    "Event_NewArena6": "Arena 6 Deckbuilding Challenge",
    "Event_NewArena7": "Arena 7 Deckbuilding Challenge",
    "Event_NewArena8": "Arena 8 Deckbuilding Challenge",
    "Event_NewArena9": "Arena 9 Deckbuilding Challenge",
    "Event_NewArena10": "Arena 10 Deckbuilding Challenge",
    "Event_NewArena11": "Arena 11 Deckbuilding Challenge",
    "Rage_Tournament": "Rage Battle",
    "ClassicDecks_Friendly": "Classic Decks Battle",
    "TeamVsTeam_Rage_Ladder": "2v2 Rage Mode",
    "ThreeVsThree": "3v3",
    "ThreeVsThreeHeist": "3v3 Heist",
    "Heist_Friendly": "Heist",
    "Heist_Draft": "Heist Draft",
    "Event_Shocktober": "Shocktober Challenge",
    "HeroChallenge1v1": "Heroes Challenge",
    "TeamVsTeam_TripleElixir_Ladder": "Triple Elixir Battle",
    "Heist_Tournament": "Heist",
    "SpawnPigsMode_Friendly": "Hog Race",
    "ClanWarMiniCollection_Friendly": "Clan War Deck Mode",
    "ClassicDecks_Helsinki2016": "Classic Decks: Helsinki 2016",
    "ClassicDecks_KingsCup1": "Classic Decks: King's Cup 1",
    "ClanWarMiniCollection_Ladder": "Clan War Deck Mode",
    "ClanWarMiniCollection_Tournament": "Clan War Deck Mode",
    "Boosts_Friendly": "Random Boosts",
    "Snowball_bombardment": "Snowball bombardment",
    "RampUpElixirSpawnPigsMode_Friendly": "Hog Race",
    "DraftSpawnPigsMode_Friendly": "Hog Race",
    "RampUpElixirSpawnPigsMode_Tournament": "Hog Race",
    "EventDeckrSpawnPigsMode_Tournament": "Hog Race",
    "RampUpElixirEventDeckSpawnPigsMode_Friendly": "Hog Race",
    "RampUpElixirDraftSpawnPigsMode_Friendly": "Hog Race",
    "TeamVsTeamSpellSupportDraft": "2v2 Draft Battle",
    "RampFatigue": "Ramp Up Fatigue Mode",
    "TestBuff": "Snowball bombardment",
    "HeroChallenge_draft2": "Heroes Challenge",
    "HeroChallenge_draft3": "Heroes Challenge",
    "ElixirCollectorCapture_Friendly": "1v1 Battle",
    "CaptureTheEgg_Friendly": "1v1 Battle",
    "DoubleDeck_Friendly": "Mega Deck",
    "DoubleDeck_Tournament": "Mega Deck",
    "RampUpElixirRageJacksMode_Tournament": "Lumberjack Rush",
    "EventDeck_Rage_SpawnJacks_Friendly": "Lumberjack Rage Rush",
    "Draft_Rage_SpawnJacks_Friendly": "Lumberjack Rage Draft",
    "ElixirCollectorCapture_Tournament": "Elixir Capture",
    "CaptureTheEgg_Tournament": "Dragon Hunt",
    "Obstacles_Friendly": "1v1 Battle",
    "Mega_Boss_PVE": "1v1 Battle",
    "CaptureTheFish_Friendly": "1v1 Battle",
    "RockyBoat_Friendly": "1v1 Battle",
    "BlindDeck_FloodHounds": "Take To The Skies",
    "Neutral_Fisherman": "1v1 Battle",
    "ClassicDecks2_Friendly": "Classic Decks Battle",
    "Heist_Ladder": "Heist",
    "RampUpElixirSpawnWBsMode_Tournament": "Wall Breaker Party",
    "RampUpElixirSpawnWBsMode_Ladder": "Wall Breaker Party",
    "RampUpElixirSpawnWBsMode_Draft": "Wall Breaker Party Draft",
    "RampUpElixirSpawnWBsMode_2v2_Tournament": "2v2 Wall Breaker Party",
    "RampUpElixirSpawnWBsMode_2v2_Draft": "2v2 Wall Breaker Party Draft",
    "RampUpElixirSpawnWBsMode_2v2_Ladder": "2v2 Wall Breaker Party",
    "RampUpElixirSpawnWBsMode_Friendly": "Wall Breaker Party",
    "NeutralFisherman_Friendly": "Wild Fisherman Battle",
    "NeutralFisherman_Tournament": "Wild Fisherman Battle",
    "NeutralFisherman_Ladder": "Wild Fisherman Battle",
    "NeutralFisherman_Draft": "Wild Fisherman Draft",
    "NeutralFisherman_Draft_2v2": "2v2 Wild Fisherman Draft",
    "NeutralFisherman_Ladder_2v2": "2v2 Wild Fisherman Battle",
    "NeutralFisherman_Tournament_2v2": "2v2 Wild Fisherman Battle",
    "NeutralFisherman_Friendly_2v2": "2v2 Wild Fisherman Battle",
    "CaptureTheFish_Tournament": "Fisherman's Catch",
    "BlindDeck_FloodHounds_2v2": "Take To The Skies",
    "EventDeck_LegsAndSpells": "Legendary Party",
    "RampUpElixirSpawnGuardsMode_Tournament": "Grave Guards",
    "RampUpElixirSpawnGuardsMode_Ladder": "Grave Guards",
    "RampUpElixirSpawnGuardsMode_Draft": "Grave Guards Draft",
    "RampUpElixirSpawnGuardsMode_2v2_Tournament": "2v2 Grave Guards",
    "RampUpElixirSpawnGuardsMode_2v2_Draft": "2v2 Grave Guards Draft",
    "RampUpElixirSpawnGuardsMode_2v2_Ladder": "2v2 Grave Guards",
    "RampUpElixirSpawnGuardsMode_Friendly": "Grave Guards",
    "SpawnGuardsMode_Tournament": "Grave Guards",
    "SpawnGuardsMode_Ladder": "Grave Guards",
    "SpawnGuardsMode_Draft": "Grave Guards Draft",
    "SpawnGuardsMode_2v2_Tournament": "2v2 Grave Guards",
    "SpawnGuardsMode_2v2_Draft": "2v2 Grave Guards Draft",
    "SpawnGuardsMode_2v2_Ladder": "2v2 Grave Guards",
    "SpawnGuardsMode_Friendly": "Grave Guards",
    "SpawnSkeletonsMode_Tournament": "Grave Guards",
    "SpawnSkeletonsMode_Ladder": "Grave Guards",
    "SpawnSkeletonsMode_Draft": "Grave Guards Draft",
    "SpawnSkeletonsMode_2v2_Tournament": "2v2 Grave Guards",
    "SpawnSkeletonsMode_2v2_Draft": "2v2 Grave Guards Draft",
    "SpawnSkeletonsMode_2v2_Ladder": "2v2 Grave Guards",
    "SpawnSkeletonsMode_Friendly": "Grave Guards",
    "NOTINUSE3": "2v2 Double Elixir",
    "RampUpElixirSpawnBanditMode_Tournament": "Bandit Dash!",
    "RampUpElixirSpawnBanditMode_Ladder": "Bandit Dash!",
    "RampUpElixirSpawnBanditMode_Draft": "Bandit Dash!",
    "RampUpElixirSpawnBanditMode_2v2_Tournament": "2v2 Bandit Dash!",
    "RampUpElixirSpawnBanditMode_2v2_Draft": "2v2 Bandit Dash Draft!",
    "RampUpElixirSpawnBanditMode_2v2_Ladder": "2v2 Bandit Dash!",
    "RampUpElixirSpawnBanditMode_Friendly": "Bandit Dash!",
    "RampUpElixirSpawnGhostMode_Tournament": "Ghost Parade",
    "RampUpElixirSpawnGhostMode_Ladder": "Ghost Parade",
    "RampUpElixirSpawnGhostMode_Draft": "Ghost Parade Draft",
    "RampUpElixirSpawnGhostMode_2v2_Tournament": "2v2 Ghost Parade",
    "RampUpElixirSpawnGhostMode_2v2_Draft": "2v2 Ghost Parade Draft",
    "RampUpElixirSpawnGhostMode_2v2_Ladder": "2v2 Ghost Parade",
    "RampUpElixirSpawnGhostMode_Friendly": "Ghost Parade",
    "RampUpElixirSkeletonParty_Friendly": "Grave Guards",
    "RampUpElixirSkeletonParty_Draft": "Grave Guards Draft",
    "RampUpElixirSkeletonParty_2v2": "2v2 Grave Guards",
    "RampUpElixirSkeletonParty_2v2_Tournament": "2v2 Grave Guards",
    "RampUpElixirSkeletonParty_Tournament": "Grave Guards",
    "RampUpElixirSkeletonParty_Ladder": "Grave Guards",
    "LegendaryParty_Blind": "Legendary Party",
    "Draft_Competitive": "Triple Draft",
    "RampUpElixirSpawnPigsMode_Ladder": "Hog Race",
    "RampUpElixirSpawnPigsMode_2v2_Ladder": "Hog Race 2v2",
    "RampUpElixirRageJacksMode_Ladder": "Lumberjack Rush",
    "RampUpElixirRageJacksMode_2v2_Ladder": "Lumberjack Rush 2v2",
    "CrownRush_Tournament": "Crown Rush",
    "TeamVsTeamLadder_CrownRush": "Crown Rush",
    "Ladder_CrownRush": "Crown Rush",
    "Event_Inter_ElixirGolemTease": "Meet the Elixir Golem",
    "Touchdown_MegaDeck_Challenge": "Touchdown",
    "Touchdown_MegaDeck_Ladder": "Touchdown",
    "RampUpElixirSpawnRamRiders_2v2_Tournament": "Ram Rider Rush!",
    "RampUpElixirSpawnRamRiders_2v2_Ladder": "Ram Rider Rush!",
    "Blind_LuckyLadies_Friendly": "Lucky Lady Decks!",
    "Event_FirecrackerTease": "Firecracker Training!",
    "RampUpElixirSpawnBalloons_2v2_Tournament": "Balloon Festival",
    "RampUpElixirSpawnBalloons_2v2_Ladder": "Balloon Festival",
    "RampUpElixirSpawnBalloons_Tournament": "Balloon Festival",
    "RampUpElixirSpawnBalloons_Ladder": "Balloon Festival",
    "ElixirCollectorCapture_Ladder": "Elixir Capture",
    "CaptureTheEgg_Ladder": "Dragon Hunt",
    "RampUpElixirDeliveryDrop_Tournament": "Royal Delivery Drop",
    "EventDeck_4orLess_TripleElixir": "SirTag's Cycle Mayhem",
    "RampUpElixirSpawnEBarbMode_Tournament": "EBarb Rush!",
    "7xElixir_Tournament": "Legendaray's Infinite Elixir",
    "RampUpElixirSpawnSparkyMode_Tournament": "WithZack's Sparky Shocker",
    "EventDeck_RoyalBirthday": "Royal Birthday Build-a-Deck!",
    "RampUpElixirDeliveryDrop_Ladder": "Royal Delivery Drop",
    "RampUpElixirSpawnRascals_2v2_Tournament": "Rascal Girl Brawl",
    "RampUpElixirSpawnRascals_2v2_Ladder": "Rascal Girl Brawl",
    "RampUpElixirSpawnRascals_Tournament": "Rascal Girl Brawl",
    "RampUpElixirSpawnRascals_Ladder": "Rascal Girl Brawl",
    "RampUpElixirSpawnEGolems_2v2_Tournament": "Nery's Elixir Extravaganza!",
    "RampUpElixirSpawnEGolems_2v2_Ladder": "Nery's Elixir Extravaganza!",
    "RampUpElixirSpawnEGolems_Tournament": "Nery's Elixir Extravaganza!",
    "RampUpElixirSpawnEGolems_Ladder": "Nery's Elixir Extravaganza!",
    "RampUpElixirSpawnEGolems_Friendly": "Nery's Elixir Extravaganza!",
    "Ranked1v1_NewArena2": "Ranked 1v1",
    "Ranked1v1_NewArena": "Ranked 1v1",
    "Challenge_AllCards_EventDeck_NoSet": "All Cards Challenge",
    "Crazy_Arena": "Chaos Mode"
};

export const getGameModeName = (gameMode) => {
    if (!gameMode) return 'Battle';
    const key = gameMode.name || gameMode.id || '';
    return GAME_MODE_MAP[key] || key || 'Battle';
};
